version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: asgiref
    versions:
    - 3.3.2
  - dependency-name: defusedxml
    versions:
    - 0.7.0
  - dependency-name: soupsieve
    versions:
    - "2.2"
  - dependency-name: django
    versions:
    - 3.1.6
  - dependency-name: urllib3
    versions:
    - 1.26.3
