language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"
  - "nightly"
jobs:
  allow_failures:
  - python: nightly
install:
  - python -m pip install --upgrade pip
  - python -m pip install -r requirements.txt
script:
  - python manage.py test
  - gprof python manage.py test
