# Generated by Django 2.2 on 2019-04-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='word',
            field=models.CharField(default='', max_length=50),
        ),
    ]
